name: Create EKS

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Create EKS cluster for environment:'
        required: true
        type: choice
        options:
          - ci
          - development
          - staging
          - production


jobs:
  make-cluster:
    runs-on: ubuntu-latest
    env:
      PLATFORM: Linux_amd64

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Echo platform
        run: |
          echo "platform is $PLATFORM"

      - name: curl
        run: |
          curl --location -O "https://github.com/eksctl-io/eksctl/releases/latest/download/eksctl_$PLATFORM.tar.gz"

      - name: ls
        run: |
          ls -l

      - name: Verify checksum
        run: |
	  curl -sL "https://github.com/eksctl-io/eksctl/releases/latest/download/eksctl_checksums.txt" | grep $PLATFORM | sha256sum --check

      - name: Untar
        run: |
	  tar -xzf eksctl_$PLATFORM.tar.gz -C /tmp && rm eksctl_$PLATFORM.tar.gz

      - name: Move to bin
        run: |
	  sudo mv /tmp/eksctl /usr/local/bin

      - name: ls bin
        run: |
	  ls -l /usr/local/bin
