name: Create EKS

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Create EKS cluster for environment:'
        required: true
        type: choice
        options:
          - ci
          - development
          - staging
          - production


jobs:
  make-cluster:
    runs-on: ubuntu-latest
    env:
      PLATFORM: Linux_amd64

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Download eksctl
        run: |
          echo "platform is $PLATFORM"
          curl --silent --location -O "https://github.com/eksctl-io/eksctl/releases/latest/download/eksctl_$PLATFORM.tar.gz" |
          echo "Listing dir" |
          ls -l
