name: Create EKS

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Create EKS cluster for environment:'
        required: true
        type: choice
        options:
          - ci
          - development
          - staging
          - production


jobs:
  make-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Install eksctl
        run: |
          # for ARM systems, set ARCH to: `arm64`, `armv6` or `armv7` |
          curl -sLO "https://github.com/eksctl-io/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" |
          # (Optional) Verify checksum |
          curl -sL "https://github.com/eksctl-io/eksctl/releases/latest/download/eksctl_checksums.txt" | grep $PLATFORM | sha256sum --check |
          tar -xzf eksctl_$PLATFORM.tar.gz -C /tmp && rm eksctl_$PLATFORM.tar.gz |
          sudo mv /tmp/eksctl /usr/local/bin


      - name: Create EKS Cluster
        run: |
          echo "Creating cluster for ${{ github.event.inputs.environment }}" |
          eksctl create cluster --name ${{ github.event.inputs.environment }}-eks-cluster --region us-west-2 --nodegroup-name my-nodes --node-type m5.large --nodes 1
