name: Manual Workflow with Dropdown

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select Deployment Environment'
        required: true
        type: choice
        options:
          - development
          - staging
          - production


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy
        run: echo "Deploying to ${{ github.event.inputs.environment }}"
        # Add your deployment script or commands here
