name: K8s Test

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Run tests on environment:'
        required: true
        type: choice
        options:
          - ci
          - development
          - staging
          - production


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Start
        run: echo "Running tests on ${{ github.event.inputs.environment }}"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.28.3'
        id: install

      - name: Update kube config
        run: aws eks update-kubeconfig --name ci-eks-cluster   

      - name: Deploy to EKS
        run: |
          kubectl apply -f dev/zookeeper-deployment.yaml
          kubectl apply -f dev/zookeeper-service.yaml
          kubectl apply -f dev/kafka-deployment.yaml
          kubectl apply -f dev/kafka-service.yaml
          kubectl apply -f dev/redis-deployment.yaml
          kubectl apply -f dev/redis-service.yaml
          kubectl apply -f dev/redis-monitor-deployment.yaml
          kubectl apply -f dev/kafka-monitor-deployment.yaml
          kubectl apply -f dev/crawler-deployment.yaml
          kubectl apply -f dev/rest-deployment.yaml
          kubectl apply -f dev/rest-service.yaml
          kubectl apply -f dev/datadoggie-deployment.yaml
          kubectl apply -f dev/datadoggie-service.yaml

      - name: Test redis-monitor
        run: |
          kubectl exec deployment/redis-monitor '/usr/src/app/run_docker_tests.sh'

      - name: Test kafka-monitor
        run: |
          kubectl exec deployment/kafka-monitor '/usr/src/app/run_docker_tests.sh'

      - name: Test rest
        run: |
          kubectl exec deployment/rest '/usr/src/app/run_docker_tests.sh'

      - name: Test crawler
        run: |
          kubectl exec deployment/crawler '/usr/src/app/run_docker_tests.sh'

      - name: Cleanup
        run: |
          kubectl delete service --all
          kubectl delete deploy --all
